# Generated by Django 4.2.4 on 2024-07-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category'),
        ('product', '0003_product_user'),
    ]

    operations = [
    ]
