# Generated by Django 4.2.4 on 2024-07-22 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_merge_0002_category_0003_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category'),
        ),
    ]
